[package]
name = 'ui'
version = '0.0.0'
authors = ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition = '2018'

[features]
widget = ['fehler','error','client-toolkit']
app = ['fehler','num','futures','async-io','futures-lite','client-toolkit','widget','sc','vector']
font = ['derive-more','fehler','ttf-parser','kurbo','image/num']
graphic = ['fehler','widget','font']
font-file = ['font','owning-ref','memmap']
text = ['unicode-segmentation','iter','num','font','widget','font-file','derive-more']
edit = ['text']
color = ['vector']
plot = ['text','color']
default = ['color','text','edit','app']

[dependencies]
iter = { path='../iter', optional=true }
num = { path='../num', optional=true }
vector = { path='../vector', optional=true }
cfg-if = ''
fehler = { version='', optional=true } # #[throws] expects {{root}}::fehler
derive-more = { version='', package='derive_more', optional=true }
owning-ref = { version='', package='owning_ref', optional=true }
error = { version='', package='anyhow', optional=true }
#futures = { version='^0.3', optional=true } # SelectAll, select_all, LocalBoxStream
futures = { version='', optional=true, package = 'futures-util' } # SelectAll, select_all, LocalBoxStream
sc = { version='', optional=true } #''
futures-lite = { version='', optional=true }
async-io = {version='', optional=true }

memmap = { version='', optional=true }
dirs = ''
xy = { path='../xy' }
image = { path='../image' }
client-toolkit = { version='', package='smithay-client-toolkit', optional=true, default-features=false }
#clipboard = { package='smithay-clipboard' } # fixme: looks complicated

kurbo = { version='', optional=true }
ttf-parser = { version='', optional=true }
unicode-segmentation = { version='', optional=true }

trace = { path='../trace', optional=true }

[[example]]
name = 'window'
path = 'examples/window.rs'
required-features = ['app']

[[example]]
name = 'text'
path = 'examples/text.rs'
required-features = ['app','text']

[[example]]
name = 'compose'
path = 'examples/compose.rs'
required-features = ['edit']

[[example]]
name = 'edit'
path = 'examples/edit.rs'
required-features = ['app','edit']

[profile.dev.package.image]
opt-level = 2
