[package]
name = 'ui'
version = '0.0.0'
authors = ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition = '2018'

[features]
#trace = ['core/trace']
#timeout = ['core/timeout']
widget = ['fehler','error','client-toolkit']
app = ['fehler','num','futures','async-io','smol','client-toolkit','widget','sc','vector']
font = ['derive-more','fehler','ttf-parser','kurbo','array','image/num']
graphic = ['xy/iter','fehler','widget','image/sRGB','font']
font-file = ['font','owning-ref','memmap']
text = ['iter','xy/iter','font','image/sRGB','widget','font-file','derive-more']
edit = ['text','unicode-segmentation']
color = []
default = ['app']

[dependencies]
iter = { path='../iter', optional=true }
array = { path='../array', optional=true }
num = { path='../num', optional=true }
vector = { path='../vector', optional=true }
cfg-if = ''
fehler = { version='', optional=true } # #[throws] expects {{root}}::fehler
derive-more = { version='', package='derive_more', optional=true }
owning-ref = { version='', package='owning_ref', optional=true }
error = { version='', package='anyhow', optional=true }
futures = { version='^0.3', optional=true } # SelectAll, select_all, LocalBoxStream
#futures = { version='', optional=true, package = 'futures-lite' }
sc = { version='', optional=true } #''
async-io = { git='https://github.com/stjepang/async-io', optional=true }
#async-io = { version='', path="../async-io", optional=true }
smol = { version='', optional=true }

memmap = { version='', optional=true }
xy = { path='../xy' }
image = { path='../image' }
client-toolkit = { version='', package='smithay-client-toolkit', optional=true, default-features=false }
#clipboard = { package='smithay-clipboard' } # fixme: looks complicated

kurbo = { version='', optional=true }
ttf-parser = { version='', optional=true }
unicode-segmentation = { version='', optional=true }

[[example]]
name = 'window'
path = 'examples/window.rs'
required-features = ['app']

[[example]]
name = 'text'
path = 'examples/text.rs'
required-features = ['app','text']

[[example]]
name = 'edit'
path = 'examples/edit.rs'
required-features = ['app','edit']

[profile.dev.package.image]
opt-level = 2
