[package]
name = "status"
version = "0.0.0"
authors = ["Matthias Fauconneau <matthias.fauconneau@gmail.com>"]
edition = "2018"

[dependencies]
parse-display = ""
anyhow = ""
tempfile = ""
memmap = ""
wayland-protocols = { version = "", features = ["unstable_protocols","client"] }
wayland-client = ""
ttf-parser = ""
