[package]
name = 'ui'
version = '0.0.0'
authors = ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition = '2018'

[features]
trace = ['core/trace']
timeout = ['core/timeout']
sRGB= ['core/array']
widget = ['client-toolkit']
app = ['core/fehler','futures','async-io','smol','client-toolkit','widget','sc']
font = ['derive-more','core/fehler','ttf-parser','kurbo']
graphic = ['xy/iter','core/fehler','widget','sRGB','font']
font-file = ['font','owning-ref','memmap']
text = ['font','sRGB','text-size','widget','font-file']
edit = ['text','core/unicode-segmentation']
color = []
default = ['app']

[dependencies]
cfg-if = ''
fehler = '' # #[throws] expects {{root}}::fehler
derive-more = { package='derive_more', version='', optional=true }
owning-ref = { package='owning_ref', version='', optional=true }
core = { path='../core' }
futures = { version='^0.3', optional=true } # SelectAll, select_all, LocalBoxStream
#futures = { version='', optional=true, package = 'futures-lite' }
sc = { optional=true } #''
async-io = { git='https://github.com/stjepang/async-io', optional=true }
#async-io = { version='', path="../async-io", optional=true }
smol = { optional=true }

memmap = { optional=true }
xy = { path='../xy' }
image = { path='../image', features = ['sRGB'] }
client-toolkit = { package='smithay-client-toolkit', optional=true, default-features=false }
#clipboard = { package='smithay-clipboard' } # fixme: looks complicated

kurbo = { optional=true }
ttf-parser = { optional=true }

text-size = { optional=true }

[[example]]
name = 'window'
path = 'examples/window.rs'
required-features = ['app']

[[example]]
name = 'text'
path = 'examples/text.rs'
required-features = ['app','text']

[[example]]
name = 'edit'
path = 'examples/edit.rs'
required-features = ['app','edit']

[profile.dev.package.image]
opt-level = 2
