[package]
name = 'framework'
version = '0.0.0'
authors = ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition = '2018'

[features]
type_ascription = []
const_fn = []
array = []
lazy_static = []
process = []
sRGB= ['array','lazy_static']
vector = []
image = ['vector']
thread = []
window = ['image','tempfile','memmap','wayland-protocols','wayland-client','rental']
text = ['ttf-parser','sRGB','thread','window','rental']
color = ['vector']
color_sRGB = ['color','sRGB','type_ascription']
#default = []

[dependencies]
anyhow = { version ='', optional=true }
fehler = { version='', optional=true }
rental = { version='', optional=true }
tempfile = { version='', optional=true }
memmap = { version='', optional=true }
wayland-protocols = { version = '', features = ['unstable_protocols','client'], optional=true }
wayland-client = { version = '', optional=true }
ttf-parser = { version='', optional=true }

[[example]]
name = 'text'
path = 'examples/text.rs'
required-features = ['text']
