[package]
name = 'framework'
version = '0.0.0'
authors = ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition = '2018'

[features]
trace = ['fehler', 'rstack-self']
timeout = ['trace'] # thread_spawn_unchecked
array = []
num = []
vector = ['array','num']
image = ['vector']
sRGB= ['array','lazy_static']
widget = ['image']
window = ['futures','smol','image','client-toolkit','widget']
font = ['derive-more','fehler','ttf-parser','kurbo']
graphic = ['fehler','widget','sRGB','font']
font-file = ['font','owning-ref','memmap']
text = ['font','sRGB','text-size','widget','font-file','lazy_static']
color = ['vector','image']
default = ['anyhow','fehler','window'] # fehler::throws should $crate

[dependencies]
cfg-if = ''
fehler = { version='', optional=true }
anyhow = { version='', optional=true }
derive-more = { package='derive_more', version='', optional=true }
lazy_static = { version='', optional=true }
owning-ref = { package='owning_ref', version='', optional=true }
futures = { version='^0.3', optional=true }
smol = { version='', optional=true }

rstack-self = { version='', features=["dw"], default-features=false, optional=true }
memmap = { version='', optional=true }
signal-hook = { version='', optional=true }

client-toolkit = { package='smithay-client-toolkit', version='', optional=true, default-features=false }

kurbo = { version='', optional=true }
ttf-parser = { version='', optional=true }

text-size = { version='', optional=true }

[[example]]
name = 'window'
path = 'examples/window.rs'
required-features = ['window']

[[example]]
name = 'text'
path = 'examples/text.rs'
required-features = ['text']
