[package]
name = 'framework'
version = '0.0.0'
authors = ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition = '2018'

[features]
trace = ['fehler', 'rstack-self']
timeout = [] # thread_spawn_unchecked
array = []
vector = ['array']
image = ['vector']
sRGB= ['array']
widget = ['image','num_enum']
window = ['futures','smol','image','client-toolkit','widget']
font = ['derive-more','fehler','ttf-parser','kurbo']
graphic = ['fehler','widget','sRGB','font']
font-file = ['font','owning-ref','memmap']
text = ['font','sRGB','text-size','widget','font-file']
text-edit = ['text','unicode-segmentation']
color = ['image']
default = ['anyhow','fehler','window','timeout'] # fehler::throws should $crate

[dependencies]
cfg-if = ''
fehler = { version='', optional=true }
anyhow = { version='', optional=true }
derive-more = { package='derive_more', version='', optional=true }
owning-ref = { package='owning_ref', version='', optional=true }
futures = { version='^0.3', optional=true }
smol = { version='', optional=true }

rstack-self = { version='', features=["dw"], default-features=false, optional=true }
memmap = { version='', optional=true }
signal-hook = { version='', optional=true }

client-toolkit = { package='smithay-client-toolkit', version='', optional=true, default-features=false }
num_enum = { version='', optional=true }

kurbo = { version='', optional=true }
ttf-parser = { version='', optional=true }

text-size = { version='', optional=true }
unicode-segmentation = { version='', optional=true }

[[example]]
name = 'window'
path = 'examples/window.rs'
required-features = ['window']

[[example]]
name = 'text'
path = 'examples/text.rs'
required-features = ['text']
