[package]
name = 'framework'
version = '0.0.0'
authors = ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition = '2018'

[features]
trace-sigint = ['rstack-self','signal-hook']
type-ascription = []
const-fn = []
array = []
lazy-static = []
process = []
sRGB= ['array','lazy-static']
vector = []
image = ['vector']
thread = []
window = ['client-toolkit','image','rental']
color = ['vector']
color-sRGB = ['color','sRGB','type-ascription']
text = ['memmap','ttf-parser','rental','derive-more','sRGB','text-size','window']
#default = []

[dependencies]
rstack-self = { version='', features=["dw"], default-features=false, optional=true }
signal-hook = { version='', optional=true }
derive-more = { package = 'derive_more', version='', optional=true }
anyhow = { version='', optional=true }
fehler = { version='', optional=true }
memmap = { version='', optional=true }
rental = { version='', optional=true }
text-size = { version='', optional=true }
#client-toolkit = { package = 'smithay-client-toolkit', version = '', optional = true }
client-toolkit = { package = 'smithay-client-toolkit', path = '../client-toolkit', optional = true }
ttf-parser = { version='', optional=true }

[[example]]
name = 'text'
path = 'examples/text.rs'
required-features = ['text']
