[package]
name = 'ui'
version = '0.0.0'
authors = ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition = '2018'

[features]
trace = ['core/trace']
timeout = ['core/timeout']
sRGB= ['core/array']
widget = ['num_enum']
window = ['futures','smol','client-toolkit','widget']
font = ['derive-more','core/fehler','ttf-parser','kurbo']
graphic = ['core/fehler','widget','sRGB','font']
font-file = ['font','owning-ref','memmap']
text = ['font','sRGB','text-size','widget','font-file']
text-edit = ['text','unicode-segmentation']
color = []
default = ['window']

[dependencies]
cfg-if = ''
fehler = '' # #[throws] expects {{root}}::fehler
derive-more = { package='derive_more', version='', optional=true }
owning-ref = { package='owning_ref', version='', optional=true }
num_enum = { version='', optional=true }
core = { version='', path='../core' }
futures = { version='^0.3', optional=true }
smol = { version='', optional=true }

memmap = { version='', optional=true }
xy = { version='', path='../xy' }
image = { version='', path='../image', features = ['sRGB'] }
client-toolkit = { package='smithay-client-toolkit', version='', optional=true, default-features=false }

kurbo = { version='', optional=true }
ttf-parser = { version='', optional=true }

text-size = { version='', optional=true }
unicode-segmentation = { version='', optional=true }

[[example]]
name = 'window'
path = 'examples/window.rs'
required-features = ['window']

[[example]]
name = 'text'
path = 'examples/text.rs'
required-features = ['text']

[profile.dev.package.image]
opt-level = 2
