[package]
name = 'framework'
version = '0.0.0'
authors = ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition = '2018'

[features]
type_ascription = []
const_fn = []
array = []
lazy_static = []
process = []
sRGB= ['array','lazy_static']
vector = []
image = ['vector']
thread = []
window = ['smithay-client-toolkit','image','rental']
color = ['vector']
color_sRGB = ['color','sRGB','type_ascription']
text = ['memmap','ttf-parser','rental','derive_more','sRGB','text-size','window']
#default = []

[dependencies]
derive_more = { version='', optional=true }
anyhow = { version='', optional=true }
fehler = { version='', optional=true }
memmap = { version='', optional=true }
rental = { version='', optional=true }
text-size = { version='', optional=true }
smithay-client-toolkit = { version = '', optional = true }
ttf-parser = { version='', optional=true }

[[example]]
name = 'text'
path = 'examples/text.rs'
required-features = ['text']
